export const plugins = {
  menu: [
    {
      name: 'Open...',
      icon: 'folder_open',
      tagName: 'oscd-menu-open',
    },
    {
      name: 'New File...',
      icon: 'note_add',
      tagName: 'oscd-menu-new',
    },
    {
      name: 'Save...',
      icon: 'save',
      requireDoc: true,
      tagName: 'oscd-menu-save',
    },
    {
      name: 'Save File As...',
      icon: 'save',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-save-as/oscd-save-as.js#Save',
    },
    {
      name: 'Rename File...',
      icon: 'edit',
      requireDoc: true,
      src: 'https://omicronenergyoss.github.io/oscd-menu-commons/oscd-menu-file-rename.js',
    },
    {
      name: 'Close File',
      icon: 'close',
      requireDoc: true,
      src: 'https://omicronenergyoss.github.io/oscd-menu-commons/oscd-menu-file-close.js',
    },
    {
      name: 'Take Snapshot',
      icon: 'cloud_sync',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-snapshot/oscd-snapshot.js',
    },
    {
      name: 'Add IED...',
      icon: 'snippet_folder',
      requireDoc: true,
      src: 'https://openenergytools.github.io/scl-import-ied/scl-import-ied.js',
    },
    {
      name: 'Update IEDs...',
      icon: 'queue',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-import-ieds/oscd-import-ieds.js',
    },
    {
      name: 'Add Templates IEDs...',
      icon: 'package_2',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-import-templates/oscd-import-templates.js',
    },
    {
      name: 'Rename IEDs...',
      icon: 'edit',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-rename-ieds/oscd-rename-ieds.js',
    },
    {
      name: 'Extract IEDs...',
      icon: 'content_cut',
      requireDoc: true,
      src: 'https://meinberg-sync.github.io/mbg-ied-extractor/mbg-icd-extractor.js',
    },
    {
      name: 'Remove IEDs...',
      icon: 'delete',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-remove-ieds/oscd-remove-ieds.js',
    },
    {
      name: 'Add Network Data',
      icon: 'network_check',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-network-data/oscd-network-data.js',
    },
    {
      name: 'Automatic Backups...',
      icon: 'timelapse',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-automatic-backup/oscd-automatic-backup.js',
    },
    {
      name: 'Subscriber LB Siemens...',
      icon: 'autorenew',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-subscriber-lb-siemens/oscd-subscriber-lb-siemens.js',
    },
    {
      name: 'Subscriber LB SEL...',
      icon: 'autorenew',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-subscriber-lb-sel/oscd-subscriber-lb-sel.js',
    },
    {
      name: 'Subscriber LB NR Electric...',
      icon: 'autorenew',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-subscriber-lb-nr/oscd-subscriber-lb-nr.js',
    },
    {
      name: 'SCL Validating...',
      icon: 'rule_folder',
      requireDoc: true,
      src: 'https://openenergytools.github.io/scl-validating/scl-validating.js',
    },
  ],
  editor: [
    {
      name: 'Design Substation',
      icon: 'add_box',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-designer/oscd-designer.js',
    },
    {
      name: 'Edit Substation',
      icon: 'margin',
      requireDoc: true,
      src: 'https://OpenEnergyTools.github.io/scl-substation-editor/scl-substation-editor.js',
    },
    {
      name: 'View Communication',
      icon: 'network_node',
      requireDoc: true,
      src: 'https://danyill.github.io/scl-communication-editor/scl-communication-editor.js',
    },
    {
      name: 'Explore Communication',
      icon: 'lan',
      requireDoc: true,
      src: 'https://sprinteins.github.io/oscd-plugins/oscd-plugins.js',
    },
    {
      name: 'Edit Communication',
      icon: 'edit',
      requireDoc: true,
      src: 'https://openenergytools.github.io/scl-communication/scl-communication.js',
    },
    {
      name: 'Subscribe (Later Binding)',
      icon: 'link',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-subscriber-later-binding/oscd-subscriber-later-binding.js',
    },
    {
      name: 'Supervise',
      icon: 'ecg',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-supervision/oscd-supervision.js',
    },
    {
      name: 'Stencil',
      icon: 'draw_collage',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-stencil/oscd-stencil.js',
    },
    {
      name: 'Publish',
      icon: 'publish',
      requireDoc: true,
      src: 'https://com-pas.github.io/oscd-publisher/oscd-publisher.js',
    },
    {
      name: 'Address Multicast (TP)',
      icon: 'auto_fix_normal',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-tp-multicast-naming/oscd-tp-multicast-naming.js',
    },
    {
      name: 'Configure Network (TP)',
      icon: 'news',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-network-config/oscd-network-config.js',
    },
    {
      name: 'Compare',
      icon: 'compare',
      requireDoc: true,
      src: 'https://OMICRONEnergyOSS.github.io/oscd-editor-diff/oscd-editor-diff.js',
    },
    {
      name: 'Source Editor',
      icon: 'code',
      requireDoc: true,
      tagName: 'oscd-editor-source',
    },
    {
      name: 'Describe',
      icon: 'description',
      requireDoc: true,
      src: 'https://danyill.github.io/oscd-description/oscd-description.js',
    },
  ],
  background: [
    {
      name: 'EditV1 Events Listener',
      icon: 'none',
      requireDoc: true,
      tagName: 'oscd-background-editv1',
    },
    {
      name: 'Wizard Events Listener',
      icon: 'none',
      requireDoc: true,
      tagName: 'oscd-background-wizard-events',
    },
  ],
};
